[package]
name = "pyo3_wrapped_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
core_lib = { path = "../core_lib" }
pyo3 = { version = "0.28.2", default-features = false, features = [
  "macros",
  "multiple-pymethods",
] }
bitvec = { version = "1.0.1", default-features = false, features = [
  "std",
  "atomic",
] }
